<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xml="http://www.w3.org/XML/1998/namespace"
	elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

	<!-- INFO: te dziwne nazwy elementow i atrybutow to optymalizacje -->

	<xsd:element name="dictionaryIndex">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="entryIndex" minOccurs="0" maxOccurs="1" type="entryIndex" />
				<xsd:element name="nameEntryIndex" minOccurs="0" maxOccurs="1" type="entryIndex" />
				<xsd:element name="kanjiCharacterInfoListIndex" minOccurs="0" maxOccurs="1" type="entryIndex" />
			</xsd:sequence>			
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="entryIndex">
		<xsd:sequence>
			<xsd:element name="japaneseIndexSectionIndex" minOccurs="1" maxOccurs="unbounded" type="sectionIndexMetadata" />
			<xsd:element name="polishIndexSectionIndex" minOccurs="1" maxOccurs="unbounded" type="sectionIndexMetadata" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="sectionIndexMetadata">
		<xsd:sequence>
			<xsd:element name="sectionName" minOccurs="1" maxOccurs="1" type="xsd:string" />
			<xsd:element name="partNo" minOccurs="1" maxOccurs="1" type="xsd:integer" />
			<xsd:element name="fileName" minOccurs="1" maxOccurs="1" type="xsd:string" />
		</xsd:sequence>	
	</xsd:complexType>
	
	<xsd:element name="sectionIndex">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="sectionName" minOccurs="1" maxOccurs="1" type="xsd:string" />
				<xsd:element name="s" minOccurs="1" maxOccurs="unbounded" type="sectionEntry" /> <!-- sectionEntry -->
				<xsd:element name="partNo" minOccurs="1" maxOccurs="1" type="xsd:integer" />				
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>	

	<xsd:complexType name="sectionEntry">
		<xsd:sequence>
			<xsd:element name="e" minOccurs="1" maxOccurs="unbounded" type="sectionEntryIndexEntry" /> <!-- entries -->
		</xsd:sequence>
		<xsd:attribute name="k" use="optional" type="xsd:string" /> <!-- kana -->
		<xsd:attribute name="r" use="optional" type="xsd:string" /> <!-- romaji -->
		<xsd:attribute name="p" use="optional" type="xsd:string" /> <!-- polishWord -->
	</xsd:complexType>
	
	<xsd:complexType name="sectionEntryIndexEntry">		
		<xsd:attribute name="k" use="optional" type="xsd:string" /> <!-- kanji -->
		<!-- <xsd:attribute name="kana" use="optional" type="xsd:string" /> -->
		<xsd:attribute name="i" use="required" type="xsd:integer" /> <!-- entryId -->
		<xsd:attribute name="url" use="optional" type="xsd:string" />
	</xsd:complexType>
</xsd:schema>