<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xml="http://www.w3.org/XML/1998/namespace"
	elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	
	<xsd:element name="dictionaryIndex">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="nameEntryIndex" minOccurs="0" maxOccurs="1" type="nameEntryIndex" />
			</xsd:sequence>			
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="nameEntryIndex">
		<xsd:sequence>
			<xsd:element name="japaneseIndexSectionIndex" minOccurs="1" maxOccurs="unbounded" type="japaneseIndexSectionIndex" />

		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="japaneseIndexSectionIndex">
		<xsd:sequence>
			<xsd:element name="sectionName" minOccurs="1" maxOccurs="1" type="xsd:string" />
			<xsd:element name="sectionIndex" minOccurs="1" maxOccurs="unbounded" type="sectionIndex" />
		</xsd:sequence>
	</xsd:complexType>	

	<xsd:complexType name="sectionIndex">
		<xsd:sequence>
			<xsd:element name="kana" minOccurs="1" maxOccurs="1" type="xsd:string" />
			<xsd:element name="romaji" minOccurs="1" maxOccurs="1" type="xsd:string" />
			<xsd:element name="entry" minOccurs="1" maxOccurs="unbounded" type="sectionEntryIndex" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="sectionEntryIndex">
		<xsd:sequence>
			<xsd:element name="kanji" minOccurs="0" maxOccurs="1" type="xsd:string" />
			<xsd:element name="entryId" minOccurs="0" maxOccurs="1" type="xsd:integer" />
			<xsd:element name="url" minOccurs="0" maxOccurs="1" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>